# -*- coding: utf-8 -*-
"""Thompsons Sampling.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1c7rriLt20b36pRMx_G_hTIj6iAW0wlJV

## Importing the libraries
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

dataset = pd.read_csv('Ads_CTR_Optimisation.csv')

dataset

"""## Implementing Thompsons Algorithm"""

import random
N = 10000
d = 10
ads_select = []
numbers_of_rewards_1 = [0] * d
number_of_rewards_0 = [0] * d
total_reward = 0
for n in range(0 , N):
  ad = 0
  max_random = 0
  for i in range(0 , d):
    random_beta = random.betavariate(numbers_of_rewards_1[i] +1 , number_of_rewards_0[i] +1)
    if(random_beta > max_random):
        max_random = random_beta
        ad = i
  ads_select.append(ad)
  reward = dataset.values[n , ad]
  if reward == 1:
    numbers_of_rewards_1[ad] +=1
  else:
    number_of_rewards_0[ad] +=1
  total_reward = total_reward + reward


total_reward

"""## Visualizing the algorithm"""

plt.hist(ads_select)
plt.title('Histogram of Ads Selections')
plt.xlabel('Ads')
plt.ylabel('Number of times each ad selected')
plt.show()